### ISSUE TITLE
update to work with node 0.6.x

### ISSUE THREAD

**Issue by troygoode** [dodo/node-unicodetable#2]
package.json currently restricts to 0.4.x, and installing via "npm install -f unicode" results in an error:

"Cannot find module './build/default/buffer-stream'"
